http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]

#output:
  #elasticsearch:
    #hosts: ["https://elasticsearch:9200"]
      #ssl: true
      #cacert: '/path/to/cert.pem'
